apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-earth-setting
spec:
  forms:
    - group: layout
      label: 布局
      formSchema:
        - $formkit: select
          name: post_list_layout
          label: 文章列表布局
          value: grid_3
          options:
            - label: 网格（一行三列）
              value: grid_3
            - label: 网格（一行两列）
              value: grid_2
            - label: 单条
              value: single
          help: "选择单条时，文章卡片的图片将位于左侧"
        - $formkit: select
          name: header_widget
          label: 首页顶部模块
          value: latest_post
          options:
            - label: 无
              value: none
            - label: 最新一篇文章
              value: latest_post
            - label: 文章网格（最新五篇文章）
              value: latest_post_grid
            - label: 轮播图
              value: carousel
            - label: 站点标题
              value: site_title
        - $formkit: select
          name: header_background_type
          id: header_background_type
          key: header_background_type
          label: 首页顶部背景
          value: manual
          options:
            - label: 手动设置
              value: manual
            - label: 图片
              value: image
        - $formkit: text
          if: "$get(header_background_type).value === manual"
          name: header_background
          id: header_background
          key: header_background
          label: 首页顶部背景
        - $formkit: text
          if: "$get(header_background_type).value === image"
          name: header_background_image
          id: header_background_image
          key: header_background_image
          label: 首页顶部背景图片
        - $formkit: radio
          name: content_header
          label: 文章页顶部
          value: true
          options:
            - label: 显示
              value: true
            - label: 隐藏
              value: false

    - group: sidebar
      label: 侧边栏
      formSchema:
        - $formkit: textarea
          name: widgets
          label: 小部件
          value: "profile,popular-posts,latest-comments,categories,tags"
          help: "目前提供的小部件有：profile（站点资料）, popular-posts（热门文章）, latest-comments（最新评论）, categories（文章分类）, tags（文章标签）。你可以随意组合或排序，以逗号隔开。"

    - group: footer
      label: 页脚
      formSchema:
        - $formkit: menuRadio
          name: menu
          label: 页脚菜单

    - group: beian
      label: 备案设置
      formSchema:
        - $formkit: text
          name: icp_text
          label: ICP备案号
        - $formkit: text
          name: icp_link
          label: ICP备案跳转链接
          value: https://beian.miit.gov.cn/
